teleport-requests:
  expire-seconds: 60

iris:
  server-lifecycle-alerts: true
  player-join-leave-alerts: false
  minecraft-xp:
    enabled: true
    interval-minutes: 30
    amount: 15
  account-link:
    code-expire-minutes: 10
